// <auto-generated />
using System;
using CertMentor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CertMentor.Infrastructure.Migrations
{
    [DbContext(typeof(CertMentorDbContext))]
    [Migration("20260525142734_AddIsActiveToSkillArea")]
    partial class AddIsActiveToSkillArea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CertMentor.Domain.Entities.Catalog.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Certifications", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Catalog.SkillArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<int?>("HighestWeightPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("LowestWeightPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.ToTable("SkillAreas", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Catalog.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SkillAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillAreaId");

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.ExamQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("_answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Answers");

                    b.Property<string>("_correctAnswers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CorrectAnswers");

                    b.HasKey("Id");

                    b.HasIndex("ExamSessionId");

                    b.HasIndex("TopicId");

                    b.ToTable("ExamQuestions", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsPass")
                        .HasColumnType("bit");

                    b.Property<float?>("Score")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.ToTable("ExamSessions", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.PerformanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamSessionId")
                        .HasColumnType("int");

                    b.Property<bool>("Result")
                        .HasColumnType("bit");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ExamSessionId");

                    b.ToTable("PerformanceRecords", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.SkillAreaScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PerformanceRecordId")
                        .HasColumnType("int");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<int>("SkillAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceRecordId");

                    b.HasIndex("SkillAreaId");

                    b.ToTable("SkillAreaScores", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.StudyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerformanceRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CertificationId");

                    b.HasIndex("PerformanceRecordId");

                    b.ToTable("StudyPlans", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.StudyPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MicrosoftLearnUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StudyPlanId")
                        .HasColumnType("int");

                    b.Property<int>("TimeInMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudyPlanId");

                    b.ToTable("StudyPlanItems", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExamQuestionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("_answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Answers");

                    b.HasKey("Id");

                    b.HasIndex("ExamQuestionId");

                    b.ToTable("UserAnswers", (string)null);
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Catalog.SkillArea", b =>
                {
                    b.HasOne("CertMentor.Domain.Entities.Catalog.Certification", "Certification")
                        .WithMany("SkillAreas")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Catalog.Topic", b =>
                {
                    b.HasOne("CertMentor.Domain.Entities.Catalog.SkillArea", "SkillArea")
                        .WithMany("Topics")
                        .HasForeignKey("SkillAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillArea");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.ExamQuestion", b =>
                {
                    b.HasOne("CertMentor.Domain.Entities.Exam.ExamSession", "ExamSession")
                        .WithMany("Questions")
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertMentor.Domain.Entities.Catalog.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExamSession");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.ExamSession", b =>
                {
                    b.HasOne("CertMentor.Domain.Entities.Catalog.Certification", "Certification")
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.PerformanceRecord", b =>
                {
                    b.HasOne("CertMentor.Domain.Entities.Exam.ExamSession", "ExamSession")
                        .WithMany()
                        .HasForeignKey("ExamSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamSession");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.SkillAreaScore", b =>
                {
                    b.HasOne("CertMentor.Domain.Entities.Exam.PerformanceRecord", "PerformanceRecord")
                        .WithMany("SkillAreaScores")
                        .HasForeignKey("PerformanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertMentor.Domain.Entities.Catalog.SkillArea", "SkillArea")
                        .WithMany()
                        .HasForeignKey("SkillAreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PerformanceRecord");

                    b.Navigation("SkillArea");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.StudyPlan", b =>
                {
                    b.HasOne("CertMentor.Domain.Entities.Catalog.Certification", "Certification")
                        .WithMany()
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CertMentor.Domain.Entities.Exam.PerformanceRecord", "PerformanceRecord")
                        .WithMany()
                        .HasForeignKey("PerformanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certification");

                    b.Navigation("PerformanceRecord");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.StudyPlanItem", b =>
                {
                    b.HasOne("CertMentor.Domain.Entities.Exam.StudyPlan", "StudyPlan")
                        .WithMany("StudyPlanItems")
                        .HasForeignKey("StudyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudyPlan");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.UserAnswer", b =>
                {
                    b.HasOne("CertMentor.Domain.Entities.Exam.ExamQuestion", "ExamQuestion")
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Catalog.Certification", b =>
                {
                    b.Navigation("SkillAreas");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Catalog.SkillArea", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.ExamSession", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.PerformanceRecord", b =>
                {
                    b.Navigation("SkillAreaScores");
                });

            modelBuilder.Entity("CertMentor.Domain.Entities.Exam.StudyPlan", b =>
                {
                    b.Navigation("StudyPlanItems");
                });
#pragma warning restore 612, 618
        }
    }
}
